import type { CollectionItem, ExploreCollection } from "./collection";

/**
 * Curated Aruba recommendations for the family trip (14–19 Oct 2026, two
 * vegetarian adults and baby Arjun, staying at Palm Aruba Condos in the
 * Palm Beach / Noord area). Researched by the traveler on 2026-10-06 and
 * stored as that content's review date — Atlas did not independently verify
 * hours, prices, menus, facilities or accessibility.
 *
 * Deliberately absent: exact addresses, coordinates, ratings, opening
 * hours (beyond what the research quoted), reservation availability,
 * high-chair or stroller claims, and anything that identifies the apartment.
 * Drive times are one-way planning estimates from the stay, not routing.
 *
 * Options, not bookings: importing these never touches reservations or the
 * itinerary.
 */

const REVIEWED_ON = "2026-10-06";

const SOLO_FAMILY = [
  "Adult solo time — one parent goes while the other stays with Arjun at the condo.",
  "Not a baby-friendly facility: no childcare, baby access or pool access is assumed.",
];

/** The "take turns" suggestion shown on every spa (an editable plan, not a booking). */
const TAKE_TURNS = {
  text: "Book separate appointments on different afternoons. One parent relaxes while the other stays with Arjun at the condo.",
  steps: [
    { at: "12:30", label: "Parent leaves for the spa" },
    { at: "13:00", until: "14:00", label: "Treatment" },
    { at: "14:30", approx: true, label: "Back at the condo" },
  ],
  leave: "12:30",
  back: "14:30",
};

const items: CollectionItem[] = [
  /* ------------------------------ outings ------------------------------ */
  {
    sourceKey: "aruba-butterfly-farm",
    name: "Butterfly Farm",
    aliases: ["The Butterfly Farm", "Aruba Butterfly Farm"],
    kind: "place",
    category: "nature",
    website: "https://www.thebutterflyfarm.com/visitor-information.html",
    recommendation: {
      type: "attraction",
      tier: "must_do",
      summary: "A gentle morning among butterflies, with plenty for Arjun to watch.",
      area: "Palm Beach",
      cuisine: null,
      driveMinutes: { min: 5, max: 10 },
      visitMinutes: { min: 45, max: 60 },
      treatmentMinutes: null,
      totalAwayMinutes: null,
      bestTime: "Early morning",
      tags: ["Short outing", "Near stay", "Nature", "Family outing"],
      family: ["Keep the visit short and flexible.", "Bring a carrier.", "Stroller access isn’t verified — confirm directly."],
      food: [],
      vegetarian: [],
      practical: ["Published opening time at research: 8:30 AM.", "Confirm current hours before visiting."],
      sources: ["https://www.thebutterflyfarm.com/visitor-information.html"],
      mapsQuery: "Butterfly Farm Aruba",
      price: null,
      priceNote: null,
      soloParent: false,
      turns: null,
    },
  },
  {
    sourceKey: "aruba-palm-beach",
    name: "Palm Beach",
    kind: "place",
    category: "beach",
    website: null,
    recommendation: {
      type: "beach",
      tier: "must_do",
      summary: "An easy repeat outing for a short beach visit and an early meal nearby.",
      area: "Palm Beach",
      cuisine: null,
      driveMinutes: { min: 5, max: 10 },
      visitMinutes: { min: 45, max: 90 },
      treatmentMinutes: null,
      totalAwayMinutes: null,
      bestTime: "Morning or late afternoon",
      tags: ["Near stay", "Flexible outing", "Beach", "Sunset option"],
      family: [
        "Use a carrier on the sand.",
        "Plan around shade and current conditions.",
        "Resort chairs and pools are not included.",
      ],
      food: [],
      vegetarian: [],
      practical: [
        "Palm Aruba’s FAQ advertises a Moomba Beach chair/palapa arrangement, subject to availability.",
        "Ask the Airbnb host whether this particular rental qualifies.",
        "This is an unconfirmed accommodation perk, not an entitlement.",
      ],
      sources: ["https://palmarubacondos.com/faq-condo-rentals-aruba/"],
      mapsQuery: "Palm Beach Aruba",
      price: null,
      priceNote: null,
      soloParent: false,
      turns: null,
    },
  },
  {
    sourceKey: "aruba-eagle-beach",
    name: "Eagle Beach",
    kind: "place",
    category: "beach",
    website: null,
    recommendation: {
      type: "beach",
      tier: "must_do",
      summary: "A relaxed beach morning and family photos near Aruba’s iconic fofoti trees.",
      area: "Eagle Beach",
      cuisine: null,
      driveMinutes: { min: 10, max: 15 },
      visitMinutes: { min: 60, max: 90 },
      treatmentMinutes: null,
      totalAwayMinutes: null,
      bestTime: "Morning",
      tags: ["Beach", "Family photos", "Relaxed outing"],
      family: [
        "Arrange shade.",
        "Bring baby supplies.",
        "Keep the visit flexible around heat and beach conditions.",
      ],
      food: [],
      vegetarian: [],
      practical: [],
      sources: ["https://www.aruba.com/us/things-to-do/beaches-and-coves"],
      mapsQuery: "Eagle Beach Aruba",
      price: null,
      priceNote: null,
      soloParent: false,
      turns: null,
    },
  },
  {
    sourceKey: "aruba-arashi-beach",
    name: "Arashi Beach",
    kind: "place",
    category: "beach",
    website: "https://www.aruba.com/us/explore/arashi-beach",
    recommendation: {
      type: "beach",
      tier: "recommended",
      summary: "A scenic beach option in the north for a slower morning.",
      area: "Noord",
      cuisine: null,
      driveMinutes: { min: 15, max: 20 },
      visitMinutes: { min: 60, max: 90 },
      treatmentMinutes: null,
      totalAwayMinutes: null,
      bestTime: "Morning",
      tags: ["Beach", "Northern Aruba", "Relaxed outing"],
      family: [
        "Bring shade and supplies.",
        "Swimming decisions depend on conditions that day — no beach is universally safe for infants.",
      ],
      food: [],
      vegetarian: [],
      practical: [],
      sources: ["https://www.aruba.com/us/explore/arashi-beach"],
      mapsQuery: "Arashi Beach Aruba",
      price: null,
      priceNote: null,
      soloParent: false,
      turns: null,
    },
  },
  {
    sourceKey: "aruba-philips-animal-garden",
    name: "Philip’s Animal Garden",
    aliases: ["Philips Animal Garden"],
    kind: "place",
    category: "nature",
    website: "https://www.philipsanimalgarden.com/",
    recommendation: {
      type: "attraction",
      tier: "recommended",
      summary: "A short animal-viewing visit at a rescue in Noord.",
      area: "Noord",
      cuisine: null,
      driveMinutes: { min: 10, max: 15 },
      visitMinutes: { min: 45, max: 60 },
      treatmentMinutes: null,
      totalAwayMinutes: null,
      bestTime: "Early morning",
      tags: ["Animals", "Short outing", "Family outing"],
      family: [
        "Arjun watches from a carrier or an appropriate permitted viewing area.",
        "Adults handle any animal feeding.",
      ],
      food: [],
      vegetarian: [],
      practical: ["Confirm current hours and access conditions."],
      sources: ["https://www.philipsanimalgarden.com/", "https://www.aruba.com/us/explore/philips-animal-garden"],
      mapsQuery: "Philip's Animal Garden Aruba",
      price: null,
      priceNote: null,
      soloParent: false,
      turns: null,
    },
  },
  {
    sourceKey: "aruba-baby-beach",
    name: "Baby Beach",
    kind: "place",
    category: "beach",
    website: null,
    recommendation: {
      type: "beach",
      tier: "recommended",
      summary: "A special beach excursion with a sheltered, shallow setting and a longer drive from the condo.",
      area: "Southern Aruba",
      cuisine: null,
      driveMinutes: { min: 45, max: 60 },
      visitMinutes: { min: 90, max: 120 },
      treatmentMinutes: null,
      totalAwayMinutes: null,
      bestTime: "Early morning",
      tags: ["Beach", "Longer drive", "Planned excursion"],
      family: [
        "Treat this as one deliberate outing.",
        "Bring shade, food and baby supplies.",
        "The name doesn’t guarantee infant safety — conditions decide whether entering the water is appropriate.",
      ],
      food: [],
      vegetarian: [],
      practical: [
        "The suggested time there excludes driving: allow about 90–120 minutes of round-trip driving (est.).",
        "Check that the outing and the drive back finish before the midday rest block.",
      ],
      sources: ["https://www.aruba.com/us/things-to-do/beaches-and-coves"],
      mapsQuery: "Baby Beach Aruba",
      price: null,
      priceNote: null,
      soloParent: false,
      turns: null,
    },
  },
  {
    sourceKey: "aruba-donkey-sanctuary",
    name: "Donkey Sanctuary Aruba",
    aliases: ["Donkey Sanctuary"],
    kind: "place",
    category: "nature",
    website: "https://www.aruba.com/us/explore/donkey-sanctuary",
    recommendation: {
      type: "attraction",
      tier: "optional",
      summary: "A short visit to a volunteer-run donkey rescue.",
      area: "Santa Cruz",
      cuisine: null,
      driveMinutes: { min: 25, max: 35 },
      visitMinutes: { min: 45, max: 60 },
      treatmentMinutes: null,
      totalAwayMinutes: null,
      bestTime: "Morning",
      tags: ["Animals", "Optional outing", "Family outing"],
      family: ["Keep Arjun close.", "Adults handle feeding."],
      food: [],
      vegetarian: [],
      practical: ["Confirm current visiting arrangements."],
      sources: ["https://www.aruba.com/us/explore/donkey-sanctuary"],
      mapsQuery: "Donkey Sanctuary Aruba",
      price: null,
      priceNote: null,
      soloParent: false,
      turns: null,
    },
  },

  /* ---------------------------- restaurants ---------------------------- */
  {
    sourceKey: "aruba-lindas-dutch-pancakes",
    name: "Linda’s Dutch Pancakes",
    aliases: ["Lindas Dutch Pancakes", "Linda’s Pancakes"],
    kind: "food",
    category: "restaurant",
    website: "https://lindas-aruba.com/",
    recommendation: {
      type: "restaurant",
      tier: "must_do",
      summary: "A fun breakfast stop for sweet and savory Dutch pancakes.",
      area: "Palm Beach / Noord",
      cuisine: "Dutch pancakes",
      driveMinutes: { min: 2, max: 5 },
      visitMinutes: null,
      treatmentMinutes: null,
      totalAwayMinutes: null,
      bestTime: "Breakfast",
      tags: ["Vegetarian options", "Breakfast", "Near stay"],
      family: ["High-chair availability not confirmed — ask directly."],
      food: ["Pineapple–coconut pancakes.", "Other vegetarian toppings from the current menu."],
      vegetarian: ["Check batter ingredients if avoiding eggs."],
      practical: ["Confirm current hours."],
      sources: ["https://lindas-aruba.com/"],
      mapsQuery: "Linda's Dutch Pancakes Aruba",
      price: null,
      priceNote: null,
      soloParent: false,
      turns: null,
    },
  },
  {
    sourceKey: "aruba-eduardos-hideaway",
    name: "Eduardo’s Hideaway",
    aliases: ["Eduardos Hideaway"],
    kind: "food",
    category: "cafe",
    website: "https://eduardosbeachshack.com/location-hideaway-current",
    recommendation: {
      type: "restaurant",
      tier: "recommended",
      summary: "Colorful bowls and smoothies for a casual breakfast or lunch.",
      area: "Noord",
      cuisine: "Bowls, smoothies, plant-based options",
      driveMinutes: { min: 5, max: 10 },
      visitMinutes: null,
      treatmentMinutes: null,
      totalAwayMinutes: null,
      bestTime: "Breakfast or lunch",
      tags: ["Vegetarian options", "Vegan options", "Casual", "Near stay"],
      family: [],
      food: [],
      vegetarian: ["Confirm current menu items."],
      practical: ["Use the Hideaway location, not another Eduardo’s branch.", "Confirm current hours."],
      sources: ["https://eduardosbeachshack.com/location-hideaway-current"],
      mapsQuery: "Eduardo's Hideaway Aruba",
      price: null,
      priceNote: null,
      soloParent: false,
      turns: null,
    },
  },
  {
    sourceKey: "aruba-lucca-trattoria",
    name: "Lucca Trattoria",
    kind: "food",
    category: "restaurant",
    website: "https://www.luccatrattoria.com/en/aruba",
    recommendation: {
      type: "restaurant",
      tier: "must_do",
      summary: "An easy Italian dinner with pizza, pasta, and a fun dessert option.",
      area: "Palm Beach",
      cuisine: "Italian",
      driveMinutes: { min: 5, max: 10 },
      visitMinutes: null,
      treatmentMinutes: null,
      totalAwayMinutes: null,
      bestTime: "Early dinner",
      tags: ["Vegetarian options", "Pizza", "Family dinner", "Near stay"],
      family: ["Request a high chair and stroller space."],
      food: ["Margherita pizza.", "Caprese pizza.", "Vegan chocolate dessert pizza, if still on the current menu."],
      vegetarian: ["Ask about cheese rennet if relevant.", "Confirm vegetarian stock in risotto."],
      practical: [],
      sources: ["https://www.luccatrattoria.com/en/aruba", "https://www.luccatrattoria.com/en/lucca-aruba-menu"],
      mapsQuery: "Lucca Trattoria Aruba",
      price: null,
      priceNote: null,
      soloParent: false,
      turns: null,
    },
  },
  {
    sourceKey: "aruba-tandoor-indian-grill-house",
    name: "Tandoor Indian Grill House",
    kind: "food",
    category: "restaurant",
    website: "https://tandooraruba.com/",
    recommendation: {
      type: "restaurant",
      tier: "recommended",
      summary: "A familiar Indian-food option with vegetarian and vegan choices.",
      area: "Palm Beach",
      cuisine: "Indian",
      driveMinutes: { min: 5, max: 10 },
      visitMinutes: null,
      treatmentMinutes: null,
      totalAwayMinutes: null,
      bestTime: "Dinner",
      tags: ["Vegetarian options", "Vegan options", "Comfort food", "Near stay"],
      family: [],
      food: [],
      vegetarian: ["Ask for your preferred spice levels.", "Confirm current dishes."],
      practical: ["Check takeaway availability — don’t assume delivery."],
      sources: ["https://tandooraruba.com/"],
      mapsQuery: "Tandoor Indian Grill House Aruba",
      price: null,
      priceNote: null,
      soloParent: false,
      turns: null,
    },
  },
  {
    sourceKey: "aruba-azia",
    name: "AZIA",
    kind: "food",
    category: "restaurant",
    website: "https://www.aziaaruba.com/menus",
    recommendation: {
      type: "restaurant",
      tier: "recommended",
      summary: "A Pan-Asian dinner option for a change of cuisine.",
      area: "Palm Beach",
      cuisine: "Pan-Asian",
      driveMinutes: { min: 5, max: 10 },
      visitMinutes: null,
      treatmentMinutes: null,
      totalAwayMinutes: null,
      bestTime: "Early dinner",
      tags: ["Vegetarian options", "Vegan options", "Something different", "Near stay"],
      family: ["Ask about high chairs and quieter seating."],
      food: ["Vegetable spring rolls.", "Edamame.", "Additional vegetarian dishes confirmed with staff."],
      vegetarian: [
        "Explicitly request no fish sauce, oyster sauce or seafood stock.",
        "Don’t rely on website menu labels alone — confirm vegetarian dishes with staff.",
      ],
      practical: ["Choose an early reservation."],
      sources: ["https://www.aziaaruba.com/menus"],
      mapsQuery: "AZIA restaurant Aruba",
      price: null,
      priceNote: null,
      soloParent: false,
      turns: null,
    },
  },
  {
    sourceKey: "aruba-lola-taqueria",
    name: "Lola Taqueria",
    kind: "food",
    category: "restaurant",
    website: "https://www.lolataqueria.com/menu",
    recommendation: {
      type: "restaurant",
      tier: "optional",
      summary: "A fun taco stop with advertised vegetarian options.",
      area: "Palm Beach",
      cuisine: "Mexican",
      driveMinutes: { min: 5, max: 10 },
      visitMinutes: null,
      treatmentMinutes: null,
      totalAwayMinutes: null,
      bestTime: "Early meal",
      tags: ["Vegetarian options", "Tacos", "Casual", "Lively atmosphere"],
      family: ["Prefer an early meal with the baby.", "Lively — a quiet atmosphere isn’t promised."],
      food: [],
      vegetarian: ["Confirm the current vegetarian filling.", "Confirm beans and sauces contain no meat stock or lard."],
      practical: [],
      sources: ["https://www.lolataqueria.com/menu", "https://www.lolataqueria.com/events-2"],
      mapsQuery: "Lola Taqueria Aruba",
      price: null,
      priceNote: null,
      soloParent: false,
      turns: null,
    },
  },
  {
    sourceKey: "aruba-ikes-bistro",
    name: "Ike’s Bistro",
    aliases: ["Ikes Bistro"],
    kind: "food",
    category: "restaurant",
    website: "https://www.ikesbistro.com/",
    recommendation: {
      type: "restaurant",
      tier: "recommended",
      summary: "A special dinner option with a dedicated vegan/vegetarian menu.",
      area: "Manchebo / Eagle Beach",
      cuisine: "Bistro with a dedicated vegan/vegetarian menu",
      driveMinutes: { min: 10, max: 20 },
      visitMinutes: null,
      treatmentMinutes: null,
      totalAwayMinutes: null,
      bestTime: "Early dinner",
      tags: ["Vegetarian menu", "Vegan options", "Special dinner"],
      family: ["Request a high chair and stroller space."],
      food: [],
      vegetarian: ["Confirm the current menu."],
      practical: ["Reserve an early table."],
      sources: ["https://www.ikesbistro.com/", "https://www.ikesbistro.com/arubafinedining"],
      mapsQuery: "Ike's Bistro Aruba",
      price: null,
      priceNote: null,
      soloParent: false,
      turns: null,
    },
  },

  /* -------------------------------- spas -------------------------------- */
  {
    sourceKey: "aruba-hyatt-zoia-spa",
    name: "ZoiA Spa — Hyatt Regency Aruba",
    aliases: ["ZoiA Spa", "Zoia Spa Hyatt"],
    kind: "place",
    category: "spa",
    website: "https://www.hyatt.com/en-US/spas/Zoia-Spa/treatments",
    recommendation: {
      type: "spa",
      tier: "top_pick",
      summary: "Our first pick for an easy spa appointment while the other parent stays at the condo.",
      area: "Palm Beach",
      cuisine: null,
      driveMinutes: { min: 5, max: 10 },
      visitMinutes: null,
      treatmentMinutes: 60,
      totalAwayMinutes: 120,
      bestTime: "Midday, one parent at a time",
      tags: ["Parent solo time", "Near stay", "Massage", "Reserve ahead"],
      family: SOLO_FAMILY,
      food: [],
      vegetarian: [],
      practical: [
        "Confirm that non-hotel guests can book.",
        "Confirm parking, check-in time, cancellation terms and facility access.",
      ],
      sources: ["https://www.hyatt.com/en-US/spas/Zoia-Spa/treatments"],
      mapsQuery: "ZoiA Spa Hyatt Regency Aruba",
      price: {
        label: "ZoiA Dushi Massage · 60 minutes, indoors",
        baseCents: 19500,
        currency: "USD",
        serviceChargePercent: 15,
        sundayServiceChargePercent: 25,
        caveat: "Published Oct 6, 2026 research: $195 + listed service charge. Confirm current total.",
      },
      priceNote: null,
      soloParent: true,
      turns: TAKE_TURNS,
    },
  },
  {
    sourceKey: "aruba-manchebo-spa-del-sol",
    name: "Spa del Sol — Manchebo",
    aliases: ["Spa del Sol"],
    kind: "place",
    category: "spa",
    website: "https://www.manchebo.com/wellness/spa",
    recommendation: {
      type: "spa",
      tier: "recommended",
      summary: "An atmospheric spa with open-air cabanas and a garden setting by Eagle Beach.",
      area: "Eagle Beach",
      cuisine: null,
      driveMinutes: { min: 10, max: 20 },
      visitMinutes: null,
      treatmentMinutes: 60,
      totalAwayMinutes: 120,
      bestTime: "Midday, one parent at a time",
      tags: ["Parent solo time", "Nature setting", "Massage", "Reserve ahead"],
      family: SOLO_FAMILY,
      food: [],
      vegetarian: [],
      practical: [
        "Ask about outdoor comfort at the time of your appointment.",
        "Confirm outside-guest bookings, parking and facilities.",
      ],
      sources: ["https://www.manchebo.com/wellness/spa"],
      mapsQuery: "Spa del Sol Manchebo Aruba",
      price: null,
      priceNote: "Unknown — request a current quote.",
      soloParent: true,
      turns: TAKE_TURNS,
    },
  },
  {
    sourceKey: "aruba-ritz-carlton-spa",
    name: "The Ritz-Carlton Spa",
    aliases: ["Ritz-Carlton Spa", "Ritz Carlton Spa Aruba"],
    kind: "place",
    category: "spa",
    website: "https://www.ritzcarlton.com/en/hotels/auart-the-ritz-carlton-aruba/spa/",
    recommendation: {
      type: "spa",
      tier: "optional",
      summary: "A luxury spa option if the treatment experience is a trip highlight.",
      area: "Northern Palm Beach",
      cuisine: null,
      driveMinutes: { min: 10, max: 15 },
      visitMinutes: null,
      treatmentMinutes: 60,
      totalAwayMinutes: 120,
      bestTime: "Midday, one parent at a time",
      tags: ["Parent solo time", "Luxury option", "Massage", "Reserve ahead"],
      family: [...SOLO_FAMILY, "Don’t assume access for the parent and baby waiting nearby."],
      food: [],
      vegetarian: [],
      practical: [
        "Request the current menu and complete price.",
        "Confirm outside-guest bookings and included facilities.",
      ],
      sources: ["https://www.ritzcarlton.com/en/hotels/auart-the-ritz-carlton-aruba/spa/"],
      mapsQuery: "The Ritz-Carlton Spa Aruba",
      price: null,
      priceNote: "Unknown — request a current quote.",
      soloParent: true,
      turns: TAKE_TURNS,
    },
  },
];

export const ARUBA_2026_EXPLORE: ExploreCollection = {
  id: "aruba-2026-explore",
  label: "Aruba recommendations",
  heading: "Explore Aruba",
  subheading: "Easy outings, vegetarian finds, and a little time to unwind.",
  destination: /aruba/i,
  reviewedOn: REVIEWED_ON,
  items,
};

/** Curated collections, matched to a trip by destination. */
export const COLLECTIONS = [ARUBA_2026_EXPLORE];

export function collectionById(id: string) {
  return COLLECTIONS.find((c) => c.id === id) ?? null;
}
